### ISSUE TITLE
Response.headers.iget missing in 3.3.0

### ISSUE THREAD

**Issue by rboulton** [benoitc/restkit#61]
In RestKit 3.2.3, I was using self.headers.iget() in a restkit.Response to get headers case insensitively.  (see https://github.com/rboulton/restpose/blob/master/python/restpose/resource.py#L31 for the actual code I used).

In 3.3.0, this gives an error: "AttributeError: 'IOrderedDict' object has no attribute 'iget'".  I assume this is a deliberate change (though it's not mentioned as a breaking change on the news page), but I can't see how I'm meant to access headers case insensitively now.

If there's a way which will work in 3.2.3 and 3.3.0, that'd be great, but if not, knowing the official way to do it in 3.3.0 would be great.
