### ISSUE TITLE
incoming header lines must use \r\n not just \n

### ISSUE THREAD

**Issue by drewp** [benoitc/restkit#8]
I haven't checked this out in the code or even the http spec, but when I upgraded from pre-1.0 to 1.3.1, some fetches broke because the sender was writing "Content-type: image/jpeg\n\n". Now I have to write "Content-type: image/jpeg\r\n\r\n" for the fetch to succeed.

The error on the client is below. This might be related to my other recent bug. I tried to fetch the latest git version, but my git clone always breaks.

```
return restkit.Resource(url, timeout=8).get().body
File "/usr/local/lib/python2.6/dist-packages/restkit-1.3.1-py2.6.egg/restkit/resource.py", line 135, in get
return self.request("GET", path=path, headers=headers, **params)
File "/usr/local/lib/python2.6/dist-packages/restkit-1.3.1-py2.6.egg/restkit/resource.py", line 231, in request
raise RequestError(e)
RequestError: 'bool' object has no attribute 'seek'
```

and in case anyone cares about the git problem:

```
% git clone http://github.com/benoitc/restkit.git
...
Getting pack 7a4a7ab2bc26d5f09d360b543a2983ca21ba0e04
which contains 0f4d515dbe14e426d52b4456007a3c796071c7fd
error: Unable to get pack file http://github.com/benoitc/restkit.git/objects/pack/pack-7a4a7ab2bc26d5f09d360b543a2983ca21ba0e04.pack
transfer closed with 1804158 bytes remaining to read
error: Unable to find 0f4d515dbe14e426d52b4456007a3c796071c7fd under http://github.com/benoitc/restkit.git
Cannot obtain needed object 0f4d515dbe14e426d52b4456007a3c796071c7fd
while processing commit 46f166e06f3b14672bfe448e19160e920cf4e93e.
fatal: Fetch failed.
```
